### ISSUE TITLE
Экран "Карточка" Окно "Редактировать колоду" Кнопка "Сохранить" и всплывающее сообщение

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/Cards#44]
http://joxi.ru/52aXJ4jC4qlkWm

1. При нажатии на кнопку "Сохранить" появляется всплывающее окно "Карточка успешно сохранена"
- заменить слово "Карточка" на "Колода" во всплывающем окне.
2. Убрать кнопки "На главную" и "Создать новую" и заменить их на одну кнопку "ОК"
3. Сообщение не исчезает, а висит долго отдельно от программы.

**Comment by h-shvedko** [comment]
FIXED
