### ISSUE TITLE
Экран "КарточкИИИ", кнопка "Редактировать колоду" , Окно "редактировать колоду" Нажатие на кнопку "Удалить" Добавить сообщение

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/Cards#68]
1. при нажатии на "Удалить" 1 ничего не происходит.
2. Нужно добавить всплывающее сообщение-предупреждение вида:
- Вместо сообщения 2 - написать "Вы собираетесь удалить эту колоду!"
- Вместо №3 - "Отменить"
- Вместо №4 - "Подтвердить действие"

**Comment by h-shvedko** [comment]
Готово
