### ISSUE TITLE
Экран "Карточка" Кнопка "Создать новую колоду" Окно "Создать колоду" Ненормальное поведение при сохранении новой колоді

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/Cards#73]
http://joxi.ru/xAey8d9Cpq7D9A

1. При выборе "Все" Части речи  и "Транспорт" в тематике ОЧЕНЬ долго ничего не происходит. 
2. Надо создать какой то индикатор загрузки или окно сообщения "Подождите, Идет создание колоды. Этот процесс займёт некоторое время." Кнопка "Ок" + пояление индикатора загрузки.

**Comment by h-shvedko** [comment]
FIXED
