### ISSUE TITLE
Экран "Карточка" Кнопка "Создать новую колоду" Окно "Создать колоду" Выбор "Части речи" - Все и Тематика "Все" Информационное окно.

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/Cards#82]
http://joxi.ru/bmoRBpPHxqwnWr

№1 - заменить на "Колода успешно создана!"
№2 - заменить на "начать учить" и переход на Карточки потом, конечно

**Comment by h-shvedko** [comment]
1 - готово

**Comment by h-shvedko** [comment]
2 - готово
