### ISSUE TITLE
Экран "Карточка" Окно "Карточка" Глаголы теряют отделяемую приставку, возвратность и предлоги

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/Cards#90]
1. http://joxi.ru/12MgVMafMQ6V7r
Этой инфы нет в карточке

2. http://joxi.ru/vAWWV07T1LG7qA
Добавить! Приставки, возвратную форму и Презент вот так:

 	 anschauen sichDat. (jmdn./etw.Akk.) / schaut sich ... an / schaute sich ... an / hat sich ... angeschaut

**Comment by h-shvedko** [comment]
1  - готово
2 - не имеет смысла, т.к. вся информация уже есть в инфинитиве
Для того что бы отделяемые приставки показывались в претеритум и перфект нужно вносить данные с отделяемыми приставками в таблицу в поля для претеритум и перфект
