### ISSUE TITLE
Экран "Карточки" "Выбрать колоду "Редактировать" - чтобы удалить

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/Cards#92]
http://joxi.ru/vAWWV07T1LEByA

Изменить сообщение об удалении №1:
№2 - заменить на "Вы собираетесь удалить эту колоду"
№3 - заменить на "отменить"
№4 - заменить на "Подтвердить"

**Comment by h-shvedko** [comment]
Готово
