### ISSUE TITLE
Экран "Создать колоду" - "Часть речи "Существительное "Тематика "Все". Перекидывает не туда

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/Cards#95]
http://joxi.ru/v29R7ZMH3wqWWA

1. При СОХРАНЕНИИ колоды, состоящей из Части речи "Существительное" и тематики "Все" выкидывает на Главную.
2. Сделать выкидывание в "Карточки"

**Comment by h-shvedko** [comment]
Готово
