### ISSUE TITLE
Экран "Создание колоды" Отобразить подсказку важную.

### ISSUE THREAD

**Issue by polina-shvedko** [h-shvedko/Cards#96]
Колоды не создаются, если выбрать только часть речи и не нажать ни одной КНОПКИ в тематике. 
Это причина пустышек

Значит, надо создать подсказку-сообщение - Вы забыли выбрать Тематику. 
Если нажать кнопку "Все" в тематике, то колода по фильтру Частей речи создается нормально.

**Comment by h-shvedko** [comment]
FIXED
